trigger:
- main

resources:
- repo: self

variables:
  docker_service_connection: shisanfan-docker-registry
  docker_host: registry.cn-shanghai.aliyuncs.com
  docker_image: shisanfan/dabaozhuanjia-web
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build & Push an Docker Image
      inputs:
        containerRegistry: $(docker_service_connection)
        repository: $(docker_iamge)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest
    