trigger:
  - '*'

resources:
  - repo: self

variables:
  - group: aliyun-shisanfan
  - name: docker_tag
    value: '$(Build.BuildId)'

stages:
  - stage: BuildStage
    displayName: Build Image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'shisanfan-docker-registry'
              repository: 'shisanfan/dabaozhuanjia-web'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(docker_tag)
                latest
          
          - task: CopyFiles@2
            inputs:
              SourceFolder: '.pipeline/'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
              CleanTargetFolder: true
              OverWrite: true
          
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: DeployToStaging
    displayName: "Deploy to Staging"
    dependsOn: BuildStage
    jobs:
      - deployment:
        environment: dabaozhuanjia-web-staging-env
        strategy:
          runOnce: #rolling, canary are the other strategies that are supported
            deploy:
              steps:
                - download: current

                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: '3.10'
                    addToPath: true
                    architecture: 'x64'
                
                - script: pip install -r $(Pipeline.Workspace)/drop/requirements.txt
                  displayName: Pip Install

                - script: python $(Pipeline.Workspace)/drop/publish.py
                  displayName: Push to Aliyun Function
                  env:
                    ALIBABA_CLOUD_ACCESS_KEY_ID: $(accesskey_id)
                    ALIBABA_CLOUD_ACCESS_KEY_SECRET: $(accesskey_secret)
                    DOCKER_TAG: $(docker_tag)
                
                
