trigger:
- main

resources:
- repo: self

variables:
  docker_service_connection: shisanfan-docker-registry
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build & Push an image
      inputs:
        containerRegistry: '$(docker_service_connection)'
        repository: 'shisanfan/dabaozhuanjia-web'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest
