trigger:
- main

resources:
- repo: self

variables:
  - group: 'Docker Registry Shisanfan'
  - name: docker_image
    value: shisanfan/dabaozhuanjia-web
  - name: tag
    value: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Cache@2
      displayName: Cache Task
      inputs:
        key: 'docker | "$(Agent.OS)" | cache'
        path: $(Pipeline.Workspace)/docker

    - script: |
          docker login --username=$(docker_username) --password $(docker_password) $(docker_host)
      displayName: Docker Login
      env:
        docker_password: $(docker_password)
   
    - script: |
        docker load -i $(Pipeline.Workspace)/docker/cache.tar
        ls -alh
        ls -alh $(Pipeline.Workspace)/docker/
      displayName: Docker Restore
      continueOnError: true

    - task: Docker@2
      displayName: Build & Push an image
      inputs:
        containerRegistry: '$(docker_service_connection)'
        repository: '$(docker_image)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest

    - script: |
        mkdir -p $(Pipeline.Workspace)/docker
        docker save -o $(Pipeline.Workspace)/docker/cache.tar $(docker_host)/$(docker_image):$(tag)
      displayName: Docker Save
      continueOnError: true