trigger:
- '*'

resources:
- repo: self

variables:

  - name: docker_tag
    value: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'shisanfan-docker-registry'
        repository: 'shisanfan/dabaozhuanjia-web'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(docker_tag)
          latest
